### ISSUE TITLE
All da truth is in da code

### ISSUE THREAD

**Issue by Dr-Big-Man** [ibara/cpaint#1]
Well, there are more commands to this program than documented in the readme. Try '/' in particular - else take a look at the code....

**Comment by Dr-Big-Man** [comment]
This is not an issues, isn't it? This is what the code is all about...

**Comment by ibara** [comment]
You know I wrote this code, right? It's a little strange for you to be telling me what's in my own code.
If you want to improve documentation, submit a PR.

**Comment by Dr-Big-Man** [comment]
Hi ibara. Really sorry, I didn't meant to be telling you something about your own code. Honestly I would be glad, if you could accept my sincere apologies. When I first started the program, I couldn't manage to draw anything - but then realized quickly, that command '/' is crucial. A this was (maybe deliberately?) hidden from the readme, I thought that opening such a 'non-issue' might be considered funny. I am really, really sorry and did not mean in any way to critize code or documentation. Not sure, if it would make sense, if I edit my comments and simply remove my silly remarks? As far as I can see, empty remarks would remain - couldn't find any way to remove my useless comments? Would be happy to hear back from you. And most of all, many many thanks for this highly insightful piece of code.

**Comment by ibara** [comment]
There's nothing to apologize for. But if there's something you want added to the documentation, please submit a PR.

**Comment by Dr-Big-Man** [comment]
Many thanks. Will try to submit a proper PR - never did that yet, so will be a useful learning exercise.
